# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'hello-docker-function:$(build.buildId)'

steps:
- script: |
    npm install
    docker build -f Dockerfile -t $(dockerId)/$(imageName) .
    docker login ltwlf.azurecr.io -u $(dockerId) -p $pswd
    docker push $(dockerId)/$(imageName)
  displayName: 'docker build'
